### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [yanhackcode15/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by yanhackcode15** [comment]
Good catch, Ken. Added this line and it tested fine on chrome using the device drop down to simulate different mobile devices. 
<meta name="viewport" content="width=device-width, initial-scale=1">

**Comment by kenmazaika** [comment]
Solid work, Yan.  Thumbs up.  :+1:
